-- Seed running training plans from uploaded JSON

WITH inserted_plan AS (
    INSERT INTO training_plans (
        created_by_user_id,
        title,
        description,
        primary_sport,
        difficulty,
        duration_weeks,
        recommended_workouts_per_week,
        is_system
    )
    VALUES (
        NULL,
        'Hal Higdon Intermediate 10K',
        '8-week intermediate 10K training plan adapted for Cadence. Includes easy runs, tempo workouts, interval sessions, cross-training, rest days, a tune-up race, and a goal 10K race.',
        'running'::activity_type,
        'intermediate'::training_plan_difficulty,
        8,
        6,
        true
    )
    RETURNING id
)
INSERT INTO training_plan_workouts (
    training_plan_id,
    sequence_index,
    template_day_offset,
    type,
    title,
    description,
    planned_distance_m,
    planned_duration_s,
    planned_elevation_gain_m,
    target_avg_speed_mps,
    target_power_watt
)
SELECT
    inserted_plan.id,
    workouts.sequence_index,
    workouts.template_day_offset,
    workouts.type,
    workouts.title,
    workouts.description,
    workouts.planned_distance_m,
    workouts.planned_duration_s,
    workouts.planned_elevation_gain_m,
    workouts.target_avg_speed_mps,
    workouts.target_power_watt
FROM inserted_plan
CROSS JOIN (
    VALUES
        (1, 0, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (2, 1, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (3, 2, 'running'::planned_activity_type, 'Tempo Run', 'Tempo workout. Run at comfortably hard effort with warm-up and cool-down included.', NULL, 2100, NULL, NULL, NULL),
        (4, 3, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (5, 4, 'rest'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (6, 5, 'cross_training'::planned_activity_type, 'Cross Training', 'Aerobic cross-training session. Low-impact effort such as cycling, swimming, or elliptical.', NULL, 3600, NULL, NULL, NULL),
        (7, 6, 'running'::planned_activity_type, 'Long Run', 'Comfortable long run.', 6437, NULL, NULL, NULL, NULL),
        (8, 7, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (9, 8, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 5633, NULL, NULL, NULL, NULL),
        (10, 9, 'running'::planned_activity_type, 'Intervals', '8 x 400m interval workout at roughly 5K effort with jog or walk recovery between repetitions.', 3200, NULL, NULL, NULL, NULL),
        (11, 10, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 6437, NULL, NULL, NULL, NULL),
        (12, 11, 'rest'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (13, 12, 'cross_training'::planned_activity_type, 'Cross Training', 'Aerobic cross-training session. Low-impact effort such as cycling, swimming, or elliptical.', NULL, 3600, NULL, NULL, NULL),
        (14, 13, 'running'::planned_activity_type, 'Long Run', 'Comfortable long run.', 8047, NULL, NULL, NULL, NULL),
        (15, 14, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (16, 15, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 6437, NULL, NULL, NULL, NULL),
        (17, 16, 'running'::planned_activity_type, 'Tempo Run', 'Tempo workout. Run at comfortably hard effort with warm-up and cool-down included.', NULL, 2400, NULL, NULL, NULL),
        (18, 17, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (19, 18, 'rest'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (20, 19, 'cross_training'::planned_activity_type, 'Cross Training', 'Aerobic cross-training session. Low-impact effort such as cycling, swimming, or elliptical.', NULL, 3600, NULL, NULL, NULL),
        (21, 20, 'running'::planned_activity_type, 'Long Run', 'Comfortable long run.', 9656, NULL, NULL, NULL, NULL),
        (22, 21, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (23, 22, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 7242, NULL, NULL, NULL, NULL),
        (24, 23, 'running'::planned_activity_type, 'Intervals', '9 x 400m interval workout at roughly 5K effort with jog or walk recovery between repetitions.', 3600, NULL, NULL, NULL, NULL),
        (25, 24, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 6437, NULL, NULL, NULL, NULL),
        (26, 25, 'rest'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (27, 26, 'rest'::planned_activity_type, 'Rest Day', 'Pre-race recovery day.', NULL, NULL, NULL, NULL, NULL),
        (28, 27, 'running'::planned_activity_type, '5K Tune-Up Race', 'Race effort. Optional tune-up 5K to practice pacing and race preparation.', 5000, NULL, NULL, NULL, NULL),
        (29, 28, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (30, 29, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 8047, NULL, NULL, NULL, NULL),
        (31, 30, 'running'::planned_activity_type, 'Tempo Run', 'Tempo workout. Run at comfortably hard effort with warm-up and cool-down included.', NULL, 2700, NULL, NULL, NULL),
        (32, 31, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (33, 32, 'rest'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (34, 33, 'cross_training'::planned_activity_type, 'Cross Training', 'Aerobic cross-training session. Low-impact effort such as cycling, swimming, or elliptical.', NULL, 3600, NULL, NULL, NULL),
        (35, 34, 'running'::planned_activity_type, 'Long Run', 'Comfortable long run.', 9656, NULL, NULL, NULL, NULL),
        (36, 35, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (37, 36, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 8851, NULL, NULL, NULL, NULL),
        (38, 37, 'running'::planned_activity_type, 'Intervals', '10 x 400m interval workout at roughly 5K effort with jog or walk recovery between repetitions.', 4000, NULL, NULL, NULL, NULL),
        (39, 38, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 6437, NULL, NULL, NULL, NULL),
        (40, 39, 'rest'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (41, 40, 'cross_training'::planned_activity_type, 'Cross Training', 'Aerobic cross-training session. Low-impact effort such as cycling, swimming, or elliptical.', NULL, 3600, NULL, NULL, NULL),
        (42, 41, 'running'::planned_activity_type, 'Long Run', 'Comfortable long run.', 11265, NULL, NULL, NULL, NULL),
        (43, 42, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (44, 43, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 9656, NULL, NULL, NULL, NULL),
        (45, 44, 'running'::planned_activity_type, 'Tempo Run', 'Tempo workout. Run at comfortably hard effort with warm-up and cool-down included.', NULL, 3000, NULL, NULL, NULL),
        (46, 45, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 6437, NULL, NULL, NULL, NULL),
        (47, 46, 'rest'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (48, 47, 'cross_training'::planned_activity_type, 'Cross Training', 'Aerobic cross-training session. Low-impact effort such as cycling, swimming, or elliptical.', NULL, 3600, NULL, NULL, NULL),
        (49, 48, 'running'::planned_activity_type, 'Long Run', 'Comfortable long run.', 12875, NULL, NULL, NULL, NULL),
        (50, 49, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (51, 50, 'running'::planned_activity_type, 'Easy Run', 'Easy conversational run.', 4828, NULL, NULL, NULL, NULL),
        (52, 51, 'running'::planned_activity_type, 'Intervals', '5 x 400m interval workout at roughly 5K effort with jog or walk recovery between repetitions.', 2000, NULL, NULL, NULL, NULL),
        (53, 52, 'running'::planned_activity_type, 'Shakeout Run', 'Short easy run before race weekend.', 3219, NULL, NULL, NULL, NULL),
        (54, 53, 'rest'::planned_activity_type, 'Rest Day', 'Pre-race recovery day.', NULL, NULL, NULL, NULL, NULL),
        (55, 54, 'rest'::planned_activity_type, 'Rest Day', 'Optional light recovery or complete rest before race day.', NULL, NULL, NULL, NULL, NULL),
        (56, 55, 'running'::planned_activity_type, '10K Race', 'Goal race effort. Race day execution for the full 10K.', 10000, NULL, NULL, NULL, NULL)
) AS workouts(
    sequence_index,
    template_day_offset,
    type,
    title,
    description,
    planned_distance_m,
    planned_duration_s,
    planned_elevation_gain_m,
    target_avg_speed_mps,
    target_power_watt
);

WITH inserted_plan AS (
    INSERT INTO training_plans (
        created_by_user_id,
        title,
        description,
        primary_sport,
        difficulty,
        duration_weeks,
        recommended_workouts_per_week,
        is_system
    )
    VALUES (
        NULL,
        'Hal Higdon Intermediate 1 Marathon',
        '18-week intermediate marathon training plan based on Hal Higdon''s Intermediate 1 Marathon schedule. Includes running workouts, pace runs, long runs, cross-training, rest days, a half marathon tune-up, and marathon race day.',
        'running'::activity_type,
        'intermediate'::training_plan_difficulty,
        18,
        6,
        true
    )
    RETURNING id
)
INSERT INTO training_plan_workouts (
    training_plan_id,
    sequence_index,
    template_day_offset,
    type,
    title,
    description,
    planned_distance_m,
    planned_duration_s,
    planned_elevation_gain_m,
    target_avg_speed_mps,
    target_power_watt
)
SELECT
    inserted_plan.id,
    workouts.sequence_index,
    workouts.template_day_offset,
    workouts.type,
    workouts.title,
    workouts.description,
    workouts.planned_distance_m,
    workouts.planned_duration_s,
    workouts.planned_elevation_gain_m,
    workouts.target_avg_speed_mps,
    workouts.target_power_watt
FROM inserted_plan
CROSS JOIN (
    VALUES
        (1, 0, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (2, 1, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (3, 2, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 5 miles at easy to moderate effort.', 8047, NULL, NULL, NULL, NULL),
        (4, 3, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (5, 4, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (6, 5, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 5 miles at planned marathon pace effort.', 8047, NULL, NULL, NULL, NULL),
        (7, 6, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 8 miles at easy, sustainable effort.', 12875, NULL, NULL, NULL, NULL),
        (8, 7, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (9, 8, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (10, 9, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 5 miles at easy to moderate effort.', 8047, NULL, NULL, NULL, NULL),
        (11, 10, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (12, 11, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (13, 12, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (14, 13, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 9 miles at easy, sustainable effort.', 14484, NULL, NULL, NULL, NULL),
        (15, 14, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (16, 15, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (17, 16, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 5 miles at easy to moderate effort.', 8047, NULL, NULL, NULL, NULL),
        (18, 17, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (19, 18, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (20, 19, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 5 miles at planned marathon pace effort.', 8047, NULL, NULL, NULL, NULL),
        (21, 20, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 6 miles at easy, sustainable effort.', 9656, NULL, NULL, NULL, NULL),
        (22, 21, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (23, 22, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (24, 23, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 6 miles at easy to moderate effort.', 9656, NULL, NULL, NULL, NULL),
        (25, 24, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (26, 25, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (27, 26, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 6 miles at planned marathon pace effort.', 9656, NULL, NULL, NULL, NULL),
        (28, 27, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 11 miles at easy, sustainable effort.', 17703, NULL, NULL, NULL, NULL),
        (29, 28, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (30, 29, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (31, 30, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 6 miles at easy to moderate effort.', 9656, NULL, NULL, NULL, NULL),
        (32, 31, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (33, 32, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (34, 33, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 6 miles at comfortable conversational effort.', 9656, NULL, NULL, NULL, NULL),
        (35, 34, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 12 miles at easy, sustainable effort.', 19312, NULL, NULL, NULL, NULL),
        (36, 35, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (37, 36, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (38, 37, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 5 miles at easy to moderate effort.', 8047, NULL, NULL, NULL, NULL),
        (39, 38, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (40, 39, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (41, 40, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 6 miles at planned marathon pace effort.', 9656, NULL, NULL, NULL, NULL),
        (42, 41, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 9 miles at easy, sustainable effort.', 14484, NULL, NULL, NULL, NULL),
        (43, 42, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (44, 43, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (45, 44, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 7 miles at easy to moderate effort.', 11265, NULL, NULL, NULL, NULL),
        (46, 45, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (47, 46, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (48, 47, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 7 miles at planned marathon pace effort.', 11265, NULL, NULL, NULL, NULL),
        (49, 48, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 14 miles at easy, sustainable effort.', 22531, NULL, NULL, NULL, NULL),
        (50, 49, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (51, 50, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (52, 51, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 7 miles at easy to moderate effort.', 11265, NULL, NULL, NULL, NULL),
        (53, 52, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (54, 53, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (55, 54, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 7 miles at comfortable conversational effort.', 11265, NULL, NULL, NULL, NULL),
        (56, 55, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 15 miles at easy, sustainable effort.', 24140, NULL, NULL, NULL, NULL),
        (57, 56, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (58, 57, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (59, 58, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 5 miles at easy to moderate effort.', 8047, NULL, NULL, NULL, NULL),
        (60, 59, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (61, 60, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (62, 61, 'rest'::planned_activity_type, 'Rest Day', 'Rest or very light shakeout. Keep effort minimal ahead of race effort.', NULL, NULL, NULL, NULL, NULL),
        (63, 62, 'running'::planned_activity_type, 'Half Marathon', 'Race or race-effort long run. Half Marathon effort day.', 21097, NULL, NULL, NULL, NULL),
        (64, 63, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (65, 64, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (66, 65, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 8 miles at easy to moderate effort.', 12875, NULL, NULL, NULL, NULL),
        (67, 66, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (68, 67, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (69, 68, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 8 miles at planned marathon pace effort.', 12875, NULL, NULL, NULL, NULL),
        (70, 69, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 17 miles at easy, sustainable effort.', 27359, NULL, NULL, NULL, NULL),
        (71, 70, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (72, 71, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (73, 72, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 8 miles at easy to moderate effort.', 12875, NULL, NULL, NULL, NULL),
        (74, 73, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (75, 74, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (76, 75, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 8 miles at comfortable conversational effort.', 12875, NULL, NULL, NULL, NULL),
        (77, 76, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 18 miles at easy, sustainable effort.', 28968, NULL, NULL, NULL, NULL),
        (78, 77, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (79, 78, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (80, 79, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 5 miles at easy to moderate effort.', 8047, NULL, NULL, NULL, NULL),
        (81, 80, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (82, 81, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (83, 82, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 8 miles at planned marathon pace effort.', 12875, NULL, NULL, NULL, NULL),
        (84, 83, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 13 miles at easy, sustainable effort.', 20921, NULL, NULL, NULL, NULL),
        (85, 84, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (86, 85, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (87, 86, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 8 miles at easy to moderate effort.', 12875, NULL, NULL, NULL, NULL),
        (88, 87, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (89, 88, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (90, 89, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 5 miles at planned marathon pace effort.', 8047, NULL, NULL, NULL, NULL),
        (91, 90, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 20 miles at easy, sustainable effort.', 32187, NULL, NULL, NULL, NULL),
        (92, 91, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (93, 92, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (94, 93, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 5 miles at easy to moderate effort.', 8047, NULL, NULL, NULL, NULL),
        (95, 94, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (96, 95, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (97, 96, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 8 miles at comfortable conversational effort.', 12875, NULL, NULL, NULL, NULL),
        (98, 97, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 12 miles at easy, sustainable effort.', 19312, NULL, NULL, NULL, NULL),
        (99, 98, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (100, 99, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (101, 100, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 8 miles at easy to moderate effort.', 12875, NULL, NULL, NULL, NULL),
        (102, 101, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (103, 102, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (104, 103, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 5 miles at planned marathon pace effort.', 8047, NULL, NULL, NULL, NULL),
        (105, 104, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 20 miles at easy, sustainable effort.', 32187, NULL, NULL, NULL, NULL),
        (106, 105, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (107, 106, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (108, 107, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 6 miles at easy to moderate effort.', 9656, NULL, NULL, NULL, NULL),
        (109, 108, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 5 miles at comfortable conversational effort.', 8047, NULL, NULL, NULL, NULL),
        (110, 109, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (111, 110, 'running'::planned_activity_type, 'Pace Run', 'Pace workout. 4 miles at planned marathon pace effort.', 6437, NULL, NULL, NULL, NULL),
        (112, 111, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 12 miles at easy, sustainable effort.', 19312, NULL, NULL, NULL, NULL),
        (113, 112, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (114, 113, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (115, 114, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 5 miles at easy to moderate effort.', 8047, NULL, NULL, NULL, NULL),
        (116, 115, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 4 miles at comfortable conversational effort.', 6437, NULL, NULL, NULL, NULL),
        (117, 116, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (118, 117, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (119, 118, 'running'::planned_activity_type, 'Long Run', 'Long aerobic run. 8 miles at easy, sustainable effort.', 12875, NULL, NULL, NULL, NULL),
        (120, 119, 'cross_training'::planned_activity_type, 'Cross Training', 'Cross-training day. Non-running aerobic activity such as cycling, swimming, rowing, or elliptical. Keep effort moderate.', NULL, NULL, NULL, NULL, NULL),
        (121, 120, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 3 miles at comfortable conversational effort.', 4828, NULL, NULL, NULL, NULL),
        (122, 121, 'running'::planned_activity_type, 'Midweek Run', 'Steady aerobic run. 4 miles at easy to moderate effort.', 6437, NULL, NULL, NULL, NULL),
        (123, 122, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (124, 123, 'rest'::planned_activity_type, 'Rest Day', 'Rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (125, 124, 'running'::planned_activity_type, 'Easy Run', 'Easy run. 2 miles at comfortable conversational effort.', 3219, NULL, NULL, NULL, NULL),
        (126, 125, 'running'::planned_activity_type, 'Marathon', 'Race day. Marathon effort.', 42195, NULL, NULL, NULL, NULL)
) AS workouts(
    sequence_index,
    template_day_offset,
    type,
    title,
    description,
    planned_distance_m,
    planned_duration_s,
    planned_elevation_gain_m,
    target_avg_speed_mps,
    target_power_watt
);
