-- Seed original Cadent road biking training plans.

WITH inserted_plan AS (
    INSERT INTO training_plans (
        created_by_user_id,
        title,
        description,
        primary_activity_type,
        difficulty,
        duration_weeks,
        recommended_workouts_per_week,
        is_system
    )
    VALUES (
        NULL,
        'Cadent Beginner Road 50K',
        '8-week beginner road biking plan for building up to a comfortable 50 km ride. Uses three rides per week, easy endurance work, basic bike handling, short tempo efforts, long rides, and rest days.',
        'road_biking'::activity_type,
        'beginner'::training_plan_difficulty,
        8,
        3,
        true
    )
    RETURNING id
)
INSERT INTO training_plan_workouts (
    training_plan_id,
    sequence_index,
    template_day_offset,
    type,
    title,
    description,
    planned_distance_m,
    planned_duration_s,
    planned_elevation_gain_m,
    target_avg_speed_mps,
    target_power_watt
)
SELECT
    inserted_plan.id,
    workouts.sequence_index,
    workouts.template_day_offset,
    workouts.type,
    workouts.title,
    workouts.description,
    workouts.planned_distance_m::numeric(12, 2),
    workouts.planned_duration_s::integer,
    workouts.planned_elevation_gain_m::numeric(10, 2),
    workouts.target_avg_speed_mps::numeric(10, 3),
    workouts.target_power_watt::integer
FROM inserted_plan
CROSS JOIN (
    VALUES
        (1, 0, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (2, 1, 'road_biking'::planned_activity_type, 'Easy Endurance Ride', '30 min easy ride at RPE 2 to 3. Stay conversational and focus on comfort on the bike.', NULL, 1800, NULL, NULL, NULL),
        (3, 2, 'resting'::planned_activity_type, 'Rest or Mobility', 'Rest day. Optional light mobility or easy walking if desired.', NULL, NULL, NULL, NULL, NULL),
        (4, 3, 'road_biking'::planned_activity_type, 'High Cadence Skills Ride', '30 min easy ride with 3 x 1 min high cadence efforts. Spin smoothly, not hard.', NULL, 1800, NULL, NULL, NULL),
        (5, 4, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (6, 5, 'road_biking'::planned_activity_type, 'Long Easy Ride', '45 min easy ride at RPE 2 to 3. Keep effort relaxed and comfortable.', NULL, 2700, NULL, NULL, NULL),
        (7, 6, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day or gentle stretching.', NULL, NULL, NULL, NULL, NULL),
        (8, 7, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (9, 8, 'road_biking'::planned_activity_type, 'Easy Endurance Ride', '35 min easy ride at RPE 2 to 3. Keep the effort conversational.', NULL, 2100, NULL, NULL, NULL),
        (10, 9, 'resting'::planned_activity_type, 'Rest or Mobility', 'Rest day. Optional light mobility or easy walking if desired.', NULL, NULL, NULL, NULL, NULL),
        (11, 10, 'road_biking'::planned_activity_type, 'Bike Handling Ride', '35 min easy ride with relaxed cornering and braking practice in a safe area.', NULL, 2100, NULL, NULL, NULL),
        (12, 11, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (13, 12, 'road_biking'::planned_activity_type, 'Long Easy Ride', '60 min easy ride at RPE 2 to 3. Build time in the saddle without chasing speed.', NULL, 3600, NULL, NULL, NULL),
        (14, 13, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day or gentle stretching.', NULL, NULL, NULL, NULL, NULL),
        (15, 14, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (16, 15, 'road_biking'::planned_activity_type, 'Endurance Ride', '40 min steady endurance ride at RPE 3 to 4. Smooth, controlled effort.', NULL, 2400, NULL, NULL, NULL),
        (17, 16, 'resting'::planned_activity_type, 'Rest or Mobility', 'Rest day. Optional light mobility or easy walking if desired.', NULL, NULL, NULL, NULL, NULL),
        (18, 17, 'road_biking'::planned_activity_type, 'Intro Tempo Ride', '40 min ride with 4 x 2 min tempo at RPE 5 to 6. Recover easy between efforts.', NULL, 2400, NULL, NULL, NULL),
        (19, 18, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (20, 19, 'road_biking'::planned_activity_type, 'Long Easy Ride', '75 min easy ride at RPE 2 to 3. Practice steady pacing.', NULL, 4500, NULL, NULL, NULL),
        (21, 20, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day or gentle stretching.', NULL, NULL, NULL, NULL, NULL),
        (22, 21, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (23, 22, 'road_biking'::planned_activity_type, 'Endurance Ride', '45 min endurance ride at RPE 3 to 4. Keep cadence smooth and effort controlled.', NULL, 2700, NULL, NULL, NULL),
        (24, 23, 'resting'::planned_activity_type, 'Rest or Mobility', 'Rest day. Optional light mobility or easy walking if desired.', NULL, NULL, NULL, NULL, NULL),
        (25, 24, 'road_biking'::planned_activity_type, 'High Cadence Skills Ride', '45 min easy ride with 5 x 1 min high cadence efforts. Stay relaxed through each effort.', NULL, 2700, NULL, NULL, NULL),
        (26, 25, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (27, 26, 'road_biking'::planned_activity_type, 'Long Easy Ride', '90 min easy ride at RPE 2 to 3. Keep this comfortable and sustainable.', NULL, 5400, NULL, NULL, NULL),
        (28, 27, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day or gentle stretching.', NULL, NULL, NULL, NULL, NULL),
        (29, 28, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (30, 29, 'road_biking'::planned_activity_type, 'Tempo Endurance Ride', '50 min ride with 2 x 6 min tempo at RPE 5 to 6. Recover easy between tempo blocks.', NULL, 3000, NULL, NULL, NULL),
        (31, 30, 'resting'::planned_activity_type, 'Rest or Mobility', 'Rest day. Optional light mobility or easy walking if desired.', NULL, NULL, NULL, NULL, NULL),
        (32, 31, 'road_biking'::planned_activity_type, 'Easy Recovery Ride', '45 min easy recovery ride at RPE 2. Keep the legs moving without adding fatigue.', NULL, 2700, NULL, NULL, NULL),
        (33, 32, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (34, 33, 'road_biking'::planned_activity_type, 'Long Easy Ride', '1 hr 45 min easy ride at RPE 2 to 3. Bring water and a small carb source.', NULL, 6300, NULL, NULL, NULL),
        (35, 34, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day or gentle stretching.', NULL, NULL, NULL, NULL, NULL),
        (36, 35, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (37, 36, 'road_biking'::planned_activity_type, 'Tempo Endurance Ride', '60 min ride with 3 x 6 min tempo at RPE 5 to 6. Keep the efforts controlled.', NULL, 3600, NULL, NULL, NULL),
        (38, 37, 'resting'::planned_activity_type, 'Rest or Mobility', 'Rest day. Optional light mobility or easy walking if desired.', NULL, NULL, NULL, NULL, NULL),
        (39, 38, 'road_biking'::planned_activity_type, 'Endurance Ride', '50 min steady endurance ride at RPE 3 to 4. Smooth aerobic work.', NULL, 3000, NULL, NULL, NULL),
        (40, 39, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (41, 40, 'road_biking'::planned_activity_type, 'Long Easy Ride', '2 hr easy ride at RPE 2 to 3. Practice fueling before you feel hungry.', NULL, 7200, NULL, NULL, NULL),
        (42, 41, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day or gentle stretching.', NULL, NULL, NULL, NULL, NULL),
        (43, 42, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (44, 43, 'road_biking'::planned_activity_type, 'Endurance Ride', '60 min endurance ride at RPE 3 to 4. Do not turn this into a hard ride.', NULL, 3600, NULL, NULL, NULL),
        (45, 44, 'resting'::planned_activity_type, 'Rest or Mobility', 'Rest day. Optional light mobility or easy walking if desired.', NULL, NULL, NULL, NULL, NULL),
        (46, 45, 'road_biking'::planned_activity_type, 'Short Tempo Ride', '45 min ride with 3 x 2 min tempo at RPE 5 to 6. Stay controlled and smooth.', NULL, 2700, NULL, NULL, NULL),
        (47, 46, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (48, 47, 'road_biking'::planned_activity_type, 'Peak Long Ride', '2 hr 30 min easy ride at RPE 2 to 3. This is the longest training ride before the goal week.', NULL, 9000, NULL, NULL, NULL),
        (49, 48, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day or gentle stretching.', NULL, NULL, NULL, NULL, NULL),
        (50, 49, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (51, 50, 'road_biking'::planned_activity_type, 'Easy Ride', '40 min easy ride at RPE 2 to 3. Keep it relaxed as you taper for the goal ride.', NULL, 2400, NULL, NULL, NULL),
        (52, 51, 'resting'::planned_activity_type, 'Rest or Mobility', 'Rest day. Optional light mobility or easy walking if desired.', NULL, NULL, NULL, NULL, NULL),
        (53, 52, 'road_biking'::planned_activity_type, 'Pre-Goal Openers Ride', '30 min easy ride with 3 x 30 sec relaxed openers. Stay fresh, not fatigued.', NULL, 1800, NULL, NULL, NULL),
        (54, 53, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (55, 54, 'road_biking'::planned_activity_type, '50K Goal Ride', 'Goal ride. Complete 50 km at a comfortable endurance effort. Pace conservatively and fuel regularly.', 50000, NULL, NULL, NULL, NULL),
        (56, 55, 'resting'::planned_activity_type, 'Recovery Day', 'Recovery day after the goal ride. Walk, stretch, or fully rest.', NULL, NULL, NULL, NULL, NULL)
) AS workouts(
    sequence_index,
    template_day_offset,
    type,
    title,
    description,
    planned_distance_m,
    planned_duration_s,
    planned_elevation_gain_m,
    target_avg_speed_mps,
    target_power_watt
);

WITH inserted_plan AS (
    INSERT INTO training_plans (
        created_by_user_id,
        title,
        description,
        primary_activity_type,
        difficulty,
        duration_weeks,
        recommended_workouts_per_week,
        is_system
    )
    VALUES (
        NULL,
        'Cadent Advanced Road Event Build',
        '10-week advanced road biking plan for experienced riders preparing for a hard road event, fondo, fast group ride, or long hilly ride. Includes threshold work, tempo rides, hill repeats, VO2 efforts, recovery rides, long rides, rest days, and a taper.',
        'road_biking'::activity_type,
        'advanced'::training_plan_difficulty,
        10,
        5,
        true
    )
    RETURNING id
)
INSERT INTO training_plan_workouts (
    training_plan_id,
    sequence_index,
    template_day_offset,
    type,
    title,
    description,
    planned_distance_m,
    planned_duration_s,
    planned_elevation_gain_m,
    target_avg_speed_mps,
    target_power_watt
)
SELECT
    inserted_plan.id,
    workouts.sequence_index,
    workouts.template_day_offset,
    workouts.type,
    workouts.title,
    workouts.description,
    workouts.planned_distance_m::numeric(12, 2),
    workouts.planned_duration_s::integer,
    workouts.planned_elevation_gain_m::numeric(10, 2),
    workouts.target_avg_speed_mps::numeric(10, 3),
    workouts.target_power_watt::integer
FROM inserted_plan
CROSS JOIN (
    VALUES
        (1, 0, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (2, 1, 'road_biking'::planned_activity_type, 'Threshold Intervals', '5 x 5 min threshold at RPE 7 to 8 with easy recovery between efforts. Warm up and cool down included.', NULL, 3600, NULL, NULL, NULL),
        (3, 2, 'road_biking'::planned_activity_type, 'Endurance Ride', '75 min endurance ride at RPE 3 to 4. Keep it steady and aerobic.', NULL, 4500, NULL, NULL, NULL),
        (4, 3, 'road_biking'::planned_activity_type, 'Hill Repeats', '6 x 3 min hill repeats at strong controlled effort. Recover easy between repeats.', NULL, 3600, NULL, NULL, NULL),
        (5, 4, 'road_biking'::planned_activity_type, 'Recovery Ride', '45 min recovery spin at RPE 1 to 2. Very easy effort.', NULL, 2700, NULL, NULL, NULL),
        (6, 5, 'road_biking'::planned_activity_type, 'Endurance Ride', '90 min endurance ride at RPE 3 to 4. Smooth consistent pacing.', NULL, 5400, NULL, NULL, NULL),
        (7, 6, 'road_biking'::planned_activity_type, 'Long Ride', '3 hr long ride at endurance effort. Keep most of the ride at RPE 3 to 4.', NULL, 10800, NULL, NULL, NULL),
        (8, 7, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (9, 8, 'road_biking'::planned_activity_type, 'Tempo Intervals', '4 x 8 min tempo or sweet spot at RPE 6 to 7 with easy recovery between efforts.', NULL, 4500, NULL, NULL, NULL),
        (10, 9, 'road_biking'::planned_activity_type, 'Endurance Ride', '90 min endurance ride at RPE 3 to 4. Keep it controlled.', NULL, 5400, NULL, NULL, NULL),
        (11, 10, 'road_biking'::planned_activity_type, 'Hard Hill Repeats', '8 x 2 min hard hill repeats at RPE 8. Recover easy between repeats.', NULL, 4800, NULL, NULL, NULL),
        (12, 11, 'road_biking'::planned_activity_type, 'Recovery Ride', '45 min recovery spin at RPE 1 to 2. Keep this very easy.', NULL, 2700, NULL, NULL, NULL),
        (13, 12, 'road_biking'::planned_activity_type, 'Endurance Ride', '2 hr endurance ride at RPE 3 to 4. Stay relaxed and steady.', NULL, 7200, NULL, NULL, NULL),
        (14, 13, 'road_biking'::planned_activity_type, 'Long Ride', '3 hr 30 min long ride at endurance effort. Practice fueling regularly.', NULL, 12600, NULL, NULL, NULL),
        (15, 14, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (16, 15, 'road_biking'::planned_activity_type, '30/30 Intervals', '3 sets of 10 x 30 sec hard and 30 sec easy. Keep the hard efforts sharp but repeatable.', NULL, 4500, NULL, NULL, NULL),
        (17, 16, 'road_biking'::planned_activity_type, 'Endurance Ride', '90 min endurance ride at RPE 3 to 4. Smooth aerobic work.', NULL, 5400, NULL, NULL, NULL),
        (18, 17, 'road_biking'::planned_activity_type, 'Threshold Intervals', '3 x 12 min threshold at RPE 7 to 8 with easy recovery between efforts.', NULL, 4500, NULL, NULL, NULL),
        (19, 18, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. Absorb the interval work before the weekend.', NULL, NULL, NULL, NULL, NULL),
        (20, 19, 'road_biking'::planned_activity_type, 'Tempo Endurance Ride', '2 hr ride with sections of tempo at RPE 5 to 6 if feeling good. Do not force the effort.', NULL, 7200, NULL, NULL, NULL),
        (21, 20, 'road_biking'::planned_activity_type, 'Long Ride', '4 hr long ride at endurance effort. Keep most of the ride comfortable.', NULL, 14400, NULL, NULL, NULL),
        (22, 21, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (23, 22, 'road_biking'::planned_activity_type, 'Light Tempo Ride', '60 min ride with 3 x 6 min tempo at RPE 5 to 6. This is a controlled recovery-week workout.', NULL, 3600, NULL, NULL, NULL),
        (24, 23, 'road_biking'::planned_activity_type, 'Easy Ride', '60 min easy ride at RPE 2 to 3. Keep it relaxed.', NULL, 3600, NULL, NULL, NULL),
        (25, 24, 'road_biking'::planned_activity_type, 'Light Hill Skills', '50 min ride with 5 x 2 min light hills. Stay smooth and avoid going deep.', NULL, 3000, NULL, NULL, NULL),
        (26, 25, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (27, 26, 'road_biking'::planned_activity_type, 'Endurance Ride', '75 min endurance ride at RPE 3 to 4. Keep the volume reduced this week.', NULL, 4500, NULL, NULL, NULL),
        (28, 27, 'road_biking'::planned_activity_type, 'Easy Long Ride', '2 hr 30 min easy long ride. Recovery week long ride, not a test.', NULL, 9000, NULL, NULL, NULL),
        (29, 28, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (30, 29, 'road_biking'::planned_activity_type, 'Threshold Intervals', '5 x 6 min threshold at RPE 7 to 8 with easy recovery between efforts.', NULL, 4500, NULL, NULL, NULL),
        (31, 30, 'road_biking'::planned_activity_type, 'Endurance Ride', '90 min endurance ride at RPE 3 to 4. Keep it aerobic.', NULL, 5400, NULL, NULL, NULL),
        (32, 31, 'road_biking'::planned_activity_type, 'VO2 Repeats', '10 x 1 min very hard at RPE 9 with easy recovery between efforts. Stay controlled.', NULL, 3600, NULL, NULL, NULL),
        (33, 32, 'road_biking'::planned_activity_type, 'Recovery Ride', '45 min recovery spin at RPE 1 to 2. Keep the legs loose.', NULL, 2700, NULL, NULL, NULL),
        (34, 33, 'road_biking'::planned_activity_type, 'Tempo Endurance Ride', '2 hr ride with 3 x 15 min tempo at RPE 5 to 6. Recover easy between blocks.', NULL, 7200, NULL, NULL, NULL),
        (35, 34, 'road_biking'::planned_activity_type, 'Long Ride', '4 hr long ride at endurance effort. Fuel early and often.', NULL, 14400, NULL, NULL, NULL),
        (36, 35, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (37, 36, 'road_biking'::planned_activity_type, 'Threshold Intervals', '3 x 10 min threshold at RPE 7 to 8 with easy recovery between efforts.', NULL, 4500, NULL, NULL, NULL),
        (38, 37, 'road_biking'::planned_activity_type, 'Endurance Ride', '1 hr 45 min endurance ride at RPE 3 to 4. Smooth aerobic volume.', NULL, 6300, NULL, NULL, NULL),
        (39, 38, 'road_biking'::planned_activity_type, 'Strength Hill Repeats', '6 x 4 min hill repeats at strong controlled effort. Stay seated when possible.', NULL, 5400, NULL, NULL, NULL),
        (40, 39, 'road_biking'::planned_activity_type, 'Recovery Ride', '45 min recovery spin at RPE 1 to 2. Very easy.', NULL, 2700, NULL, NULL, NULL),
        (41, 40, 'road_biking'::planned_activity_type, 'Endurance Ride', '2 hr 15 min endurance ride at RPE 3 to 4. Keep pressure steady on the pedals.', NULL, 8100, NULL, NULL, NULL),
        (42, 41, 'road_biking'::planned_activity_type, 'Long Ride', '4 hr 30 min long ride at endurance effort. Practice event-day fueling.', NULL, 16200, NULL, NULL, NULL),
        (43, 42, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (44, 43, 'road_biking'::planned_activity_type, '30/30 Intervals', '4 sets of 8 x 30 sec hard and 30 sec easy. Keep efforts repeatable, not all-out.', NULL, 5400, NULL, NULL, NULL),
        (45, 44, 'road_biking'::planned_activity_type, 'Endurance Ride', '90 min endurance ride at RPE 3 to 4. Keep it controlled after the hard session.', NULL, 5400, NULL, NULL, NULL),
        (46, 45, 'road_biking'::planned_activity_type, 'Threshold Intervals', '2 x 20 min threshold at RPE 7 to 8 with easy recovery between efforts.', NULL, 5400, NULL, NULL, NULL),
        (47, 46, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day before the peak weekend.', NULL, NULL, NULL, NULL, NULL),
        (48, 47, 'road_biking'::planned_activity_type, 'Tempo Endurance Ride', '2 hr tempo endurance ride. Include steady tempo only if the legs feel good.', NULL, 7200, NULL, NULL, NULL),
        (49, 48, 'road_biking'::planned_activity_type, 'Peak Long Ride', '5 hr long ride at endurance effort. This is the peak volume ride of the plan.', NULL, 18000, NULL, NULL, NULL),
        (50, 49, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (51, 50, 'road_biking'::planned_activity_type, 'Controlled Tempo Ride', '60 min ride with 3 x 8 min tempo at RPE 5 to 6. Keep it comfortable.', NULL, 3600, NULL, NULL, NULL),
        (52, 51, 'road_biking'::planned_activity_type, 'Easy Ride', '75 min easy ride at RPE 2 to 3. Recovery-focused endurance.', NULL, 4500, NULL, NULL, NULL),
        (53, 52, 'road_biking'::planned_activity_type, 'Controlled Hill Repeats', '60 min ride with 5 x 3 min controlled hills. Stay smooth and avoid maximal efforts.', NULL, 3600, NULL, NULL, NULL),
        (54, 53, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (55, 54, 'road_biking'::planned_activity_type, 'Endurance Ride', '90 min endurance ride at RPE 3 to 4. Reduced load to absorb fitness.', NULL, 5400, NULL, NULL, NULL),
        (56, 55, 'road_biking'::planned_activity_type, 'Easy Long Ride', '3 hr easy long ride at RPE 2 to 3. Keep it relaxed.', NULL, 10800, NULL, NULL, NULL),
        (57, 56, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (58, 57, 'road_biking'::planned_activity_type, 'Threshold Sharpening', '4 x 5 min threshold at RPE 7 to 8 with easy recovery between efforts.', NULL, 3600, NULL, NULL, NULL),
        (59, 58, 'road_biking'::planned_activity_type, 'Endurance Ride', '75 min endurance ride at RPE 3 to 4. Keep it aerobic.', NULL, 4500, NULL, NULL, NULL),
        (60, 59, 'road_biking'::planned_activity_type, 'VO2 Openers', '6 x 1 min very hard at RPE 9 with full easy recovery. Sharp but not exhausting.', NULL, 2700, NULL, NULL, NULL),
        (61, 60, 'road_biking'::planned_activity_type, 'Recovery Ride', '45 min recovery spin at RPE 1 to 2. Keep it very easy.', NULL, 2700, NULL, NULL, NULL),
        (62, 61, 'road_biking'::planned_activity_type, 'Tempo Endurance Ride', '90 min ride with 2 x 12 min tempo at RPE 5 to 6. Stay controlled.', NULL, 5400, NULL, NULL, NULL),
        (63, 62, 'road_biking'::planned_activity_type, 'Long Ride', '3 hr long ride at endurance effort. Last substantial long ride before taper.', NULL, 10800, NULL, NULL, NULL),
        (64, 63, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day. No structured training.', NULL, NULL, NULL, NULL, NULL),
        (65, 64, 'road_biking'::planned_activity_type, 'Short Hard Efforts', '45 min ride with 3 x 3 min hard but controlled at RPE 8. Keep plenty in reserve.', NULL, 2700, NULL, NULL, NULL),
        (66, 65, 'road_biking'::planned_activity_type, 'Easy Ride', '60 min easy ride at RPE 2 to 3. Keep the legs moving.', NULL, 3600, NULL, NULL, NULL),
        (67, 66, 'road_biking'::planned_activity_type, 'Pre-Event Openers', '45 min easy ride with 3 x 30 sec relaxed openers. Stay fresh.', NULL, 2700, NULL, NULL, NULL),
        (68, 67, 'resting'::planned_activity_type, 'Rest Day', 'Full rest day before the event weekend.', NULL, NULL, NULL, NULL, NULL),
        (69, 68, 'road_biking'::planned_activity_type, 'Easy Spin', '30 min very easy spin at RPE 1 to 2. Stop if the legs feel heavy.', NULL, 1800, NULL, NULL, NULL),
        (70, 69, 'road_biking'::planned_activity_type, 'Event Ride', 'Goal event ride. Ride 4 to 5 hr at planned event effort, pacing conservatively early.', NULL, 16200, NULL, NULL, NULL)
) AS workouts(
    sequence_index,
    template_day_offset,
    type,
    title,
    description,
    planned_distance_m,
    planned_duration_s,
    planned_elevation_gain_m,
    target_avg_speed_mps,
    target_power_watt
);