/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedTrainingPlansRouteImport } from './routes/_authenticated/training/plans'
import { Route as AuthenticatedDashboardTrainingIndexRouteImport } from './routes/_authenticated/dashboard/training/index'
import { Route as AuthenticatedDashboardTrainingCalendarRouteImport } from './routes/_authenticated/dashboard/training/calendar'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrainingPlansRoute =
  AuthenticatedTrainingPlansRouteImport.update({
    id: '/training/plans',
    path: '/training/plans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTrainingIndexRoute =
  AuthenticatedDashboardTrainingIndexRouteImport.update({
    id: '/dashboard/training/',
    path: '/dashboard/training/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardTrainingCalendarRoute =
  AuthenticatedDashboardTrainingCalendarRouteImport.update({
    id: '/dashboard/training/calendar',
    path: '/dashboard/training/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/training/plans': typeof AuthenticatedTrainingPlansRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/training/calendar': typeof AuthenticatedDashboardTrainingCalendarRoute
  '/dashboard/training/': typeof AuthenticatedDashboardTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/training/plans': typeof AuthenticatedTrainingPlansRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/training/calendar': typeof AuthenticatedDashboardTrainingCalendarRoute
  '/dashboard/training': typeof AuthenticatedDashboardTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/training/plans': typeof AuthenticatedTrainingPlansRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/training/calendar': typeof AuthenticatedDashboardTrainingCalendarRoute
  '/_authenticated/dashboard/training/': typeof AuthenticatedDashboardTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/training/plans'
    | '/dashboard/'
    | '/dashboard/training/calendar'
    | '/dashboard/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/training/plans'
    | '/dashboard'
    | '/dashboard/training/calendar'
    | '/dashboard/training'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/training/plans'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/training/calendar'
    | '/_authenticated/dashboard/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/training/plans': {
      id: '/_authenticated/training/plans'
      path: '/training/plans'
      fullPath: '/training/plans'
      preLoaderRoute: typeof AuthenticatedTrainingPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/training/': {
      id: '/_authenticated/dashboard/training/'
      path: '/dashboard/training'
      fullPath: '/dashboard/training/'
      preLoaderRoute: typeof AuthenticatedDashboardTrainingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/training/calendar': {
      id: '/_authenticated/dashboard/training/calendar'
      path: '/dashboard/training/calendar'
      fullPath: '/dashboard/training/calendar'
      preLoaderRoute: typeof AuthenticatedDashboardTrainingCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedTrainingPlansRoute: typeof AuthenticatedTrainingPlansRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardTrainingCalendarRoute: typeof AuthenticatedDashboardTrainingCalendarRoute
  AuthenticatedDashboardTrainingIndexRoute: typeof AuthenticatedDashboardTrainingIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTrainingPlansRoute: AuthenticatedTrainingPlansRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardTrainingCalendarRoute:
    AuthenticatedDashboardTrainingCalendarRoute,
  AuthenticatedDashboardTrainingIndexRoute:
    AuthenticatedDashboardTrainingIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
